event_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /event

event_homepage:
    path:     /hello/{name}
    defaults: { _controller: EventBundle:Default:index, name: "Pepe" }
